### ISSUE TITLE
大神，我搭建好了，但是登录不了，提示： 网络请求有误，请稍后重试!

### ISSUE THREAD

**Issue by one-mo** [52admln/vue-questionnaire#26]

**Comment by 2463091804** [comment]
![360 16560316216966](https://user-images.githubusercontent.com/29153603/47198242-a9fc2380-d39d-11e8-8900-85982d45b478.png)

**Comment by 52admln** [comment]
控制台 Network 里看一下报错

Little Mo <notifications@github.com> 于2018年10月19日周五 下午12:51写道：

**Comment by 2463091804** [comment]
[Fri Oct 19 12:41:49.249470 2018] [proxy_fcgi:error] [pid 10381] [client 110.74.214.211:61511] AH01071: Got error 'Primary script unknown\n', referer: http://ssc.503.one/dist/
[Fri Oct 19 12:41:50.435773 2018] [proxy_fcgi:error] [pid 10391] [client 110.74.214.211:61514] AH01071: Got error 'Primary script unknown\n', referer: http://ssc.503.one/dist/
[Fri Oct 19 12:41:50.616093 2018] [proxy_fcgi:error] [pid 10384] [client 110.74.214.211:61517] AH01071: Got error 'Primary script unknown\n', referer: http://ssc.503.one/dist/
[Fri Oct 19 12:41:50.805268 2018] [proxy_fcgi:error] [pid 10385] [client 110.74.214.211:61518] AH01071: Got error 'Primary script unknown\n', referer: http://ssc.503.one/dist/
[Fri Oct 19 12:41:50.979074 2018] [proxy_fcgi:error] [pid 10381] [client 110.74.214.211:61519] AH01071: Got error 'Primary script unknown\n', referer: http://ssc.503.one/dist/
[Fri Oct 19 12:42:14.721079 2018] [autoindex:error] [pid 10406] [client 110.74.214.211:61559] AH01276: Cannot serve directory /www/wwwroot/vue-questionnaire/node_modules/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Fri Oct 19 12:42:15.508758 2018] [autoindex:error] [pid 10408] [client 110.74.214.211:61560] AH01276: Cannot serve directory /www/wwwroot/vue-questionnaire/node_modules/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Fri Oct 19 12:55:59.897408 2018] [autoindex:error] [pid 12446] [client 110.74.214.211:62913] AH01276: Cannot serve directory /www/wwwroot/vue-questionnaire/src/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Fri Oct 19 12:56:13.341998 2018] [autoindex:error] [pid 12469] [client 110.74.214.211:62934] AH01276: Cannot serve directory /www/wwwroot/vue-questionnaire/build/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Fri Oct 19 12:56:14.050388 2018] [autoindex:error] [pid 12471] [client 110.74.214.211:62935] AH01276: Cannot serve directory /www/wwwroot/vue-questionnaire/build/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Fri Oct 19 12:56:29.336158 2018] [autoindex:error] [pid 12501] [client 110.74.214.211:62964] AH01276: Cannot serve directory /www/wwwroot/vue-questionnaire/config/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive, referer: http://ssc.503.one/
[Fri Oct 19 12:56:31.242720 2018] [autoindex:error] [pid 12503] [client 110.74.214.211:62965] AH01276: Cannot serve directory /www/wwwroot/vue-questionnaire/config/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Fri Oct 19 12:57:42.844545 2018] [core:error] [pid 12524] [client 110.74.214.211:63084] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://ssc.503.one/
[Fri Oct 19 12:59:53.975744 2018] [core:error] [pid 12520] [client 110.74.214.211:63290] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://ssc.503.one/
[Fri Oct 19 13:01:25.222421 2018] [autoindex:error] [pid 12616] [client 110.74.214.211:63440] AH01276: Cannot serve directory /www/wwwroot/vue-questionnaire/config/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Fri Oct 19 13:01:25.714076 2018] [autoindex:error] [pid 12621] [client 110.74.214.211:63441] AH01276: Cannot serve directory /www/wwwroot/vue-questionnaire/config/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Fri Oct 19 13:01:25.873465 2018] [autoindex:error] [pid 12619] [client 110.74.214.211:63442] AH01276: Cannot serve directory /www/wwwroot/vue-questionnaire/config/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Fri Oct 19 13:01:38.704783 2018] [autoindex:error] [pid 12647] [client 110.74.214.211:63454] AH01276: Cannot serve directory /www/wwwroot/vue-questionnaire/static/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Fri Oct 19 13:01:43.244946 2018] [autoindex:error] [pid 12666] [client 110.74.214.211:63464] AH01276: Cannot serve directory /www/wwwroot/vue-questionnaire/node_modules/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Fri Oct 19 13:01:48.770075 2018] [autoindex:error] [pid 12677] [client 110.74.214.211:63473] AH01276: Cannot serve directory /www/wwwroot/vue-questionnaire/build/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Fri Oct 19 13:01:57.307612 2018] [core:error] [pid 12694] [client 110.74.214.211:63487] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://ssc.503.one/
[Fri Oct 19 13:03:13.013883 2018] [core:error] [pid 12702] [client 110.74.214.211:63605] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://ssc.503.one/
[Fri Oct 19 13:03:13.697537 2018] [core:error] [pid 12693] [client 110.74.214.211:63607] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://ssc.503.one/
[Fri Oct 19 13:03:14.099788 2018] [core:error] [pid 12696] [client 110.74.214.211:63610] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://ssc.503.one/
[Fri Oct 19 13:08:49.226518 2018] [core:error] [pid 12693] [client 110.74.214.211:64140] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://ssc.503.one/
[Fri Oct 19 13:18:32.389585 2018] [core:error] [pid 12912] [client 110.74.214.211:65028] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://ssc.503.one/
[Fri Oct 19 13:20:00.229515 2018] [core:error] [pid 12913] [client 110.74.214.211:65171] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://ssc.503.one/

**Comment by 2463091804** [comment]
看不懂

**Comment by 52admln** [comment]
我仓库下的 api 文件夹放到网站根目录了吗？

Little Mo <notifications@github.com> 于2018年10月19日周五 下午1:47写道：

**Comment by 52admln** [comment]
#31 我代码也做了一下微调，方便部署。
